### ISSUE TITLE
dataset and code release time

### ISSUE THREAD

**Issue by lzw-lzw** [Lavender105/RSGPT#2]
Thanks for your excellent work, I wonder when the dataset and code will be open sourced

**Comment by Lavender105** [comment]
Thank you for your interest. We will release the data and code after the paper is accepted, and we will notify you at that time.

**Comment by lhackel-tub** [comment]
Just following this thread to get notified as well

**Comment by Louma20** [comment]
@Lavender105 is there any specific time or estimation for when the code and dataset will be released?

**Comment by lx709** [comment]
We have released the evaluation dataset RSIEval now, please check the README file. RSICap dataset will be released upon acceptance of the paper.
