### ISSUE TITLE
When I open the first image of RSIEval, there is an error.

### ISSUE THREAD

**Issue by xulinui** [Lavender105/RSGPT#5]
<img width="1482" alt="1" src="https://github.com/Lavender105/RSGPT/assets/66818560/5163f0f5-30ca-4556-b391-0e330e13234a">

**Comment by xulinui** [comment]
P1384_0054.png

**Comment by lx709** [comment]
Sorry for the mistake and we have already corrected this issue. The data quality is always an important thing we have in mind. Thanks for your carefulness.
